#pragma once

#include "../result.h"
#include "../api.h"
#include "../typedefs.h"

#if defined( NATUS_TARGET_OS_WIN )
#include <windows.h>
#elif defined( NATUS_TARGET_OS_LIN )
#else
#endif

#include <GL/glcorearb.h>
//#define GL_VERSION_1_1 0

#include <natus/ntd/list.hpp>

namespace natus
{
    namespace ogl
    {
        struct NATUS_OGL_API gl
        {
            natus_this_typedefs( gl ) ;

        public:

            typedef natus::ntd::list< natus::ntd::string > string_list_t ;
            static string_list_t _extensions ;

            static void_ptr_t load_gl_function( char_cptr_t name ) ;

            static bool_t _init ;

        public:

            static natus::ogl::result init( void_t ) ;

            static bool_t is_supported( char const* name ) ;
        };
    }
}

namespace natus
{
    namespace ogl
    {
    // gl version 1.0

        NATUS_OGL_API PFNGLCULLFACEPROC glCullFace ;
        NATUS_OGL_API PFNGLFRONTFACEPROC glFrontFace ;
        NATUS_OGL_API PFNGLHINTPROC glHint ;
        NATUS_OGL_API PFNGLLINEWIDTHPROC glLineWidth;
        NATUS_OGL_API PFNGLPOINTSIZEPROC glPointSize ;
        NATUS_OGL_API PFNGLPOLYGONMODEPROC glPolygonMode ;
        NATUS_OGL_API PFNGLSCISSORPROC glScissor ;
        NATUS_OGL_API PFNGLTEXPARAMETERFPROC glTexParameterf ;
        NATUS_OGL_API PFNGLTEXPARAMETERFVPROC glTexParameterfv ;
        NATUS_OGL_API PFNGLTEXPARAMETERIPROC glTexParameteri ;
        NATUS_OGL_API PFNGLTEXPARAMETERIVPROC glTexParameteriv ;
        NATUS_OGL_API PFNGLTEXIMAGE1DPROC glTexImage1D ;
        NATUS_OGL_API PFNGLTEXIMAGE2DPROC glTexImage2D ;
        NATUS_OGL_API PFNGLDRAWBUFFERPROC glDrawBuffer ;
        NATUS_OGL_API PFNGLCLEARPROC glClear ;
        NATUS_OGL_API PFNGLCLEARCOLORPROC glClearColor ;
        NATUS_OGL_API PFNGLCLEARSTENCILPROC glClearStencil ;
        NATUS_OGL_API PFNGLCLEARDEPTHPROC glClearDepth ;
        NATUS_OGL_API PFNGLSTENCILMASKPROC glStencilMask ;
        NATUS_OGL_API PFNGLCOLORMASKPROC glColorMask ;
        NATUS_OGL_API PFNGLDEPTHMASKPROC glDepthMask ;
        NATUS_OGL_API PFNGLDISABLEPROC glDisable ;
        NATUS_OGL_API PFNGLENABLEPROC glEnable ;
        NATUS_OGL_API PFNGLFINISHPROC glFinish ;
        NATUS_OGL_API PFNGLFLUSHPROC glFlush ;
        NATUS_OGL_API PFNGLBLENDFUNCPROC glBlendFunc ;
        NATUS_OGL_API PFNGLLOGICOPPROC glLogicOp ;
        NATUS_OGL_API PFNGLSTENCILFUNCPROC glStencilFunc ;
        NATUS_OGL_API PFNGLSTENCILOPPROC glStencilOp ;
        NATUS_OGL_API PFNGLDEPTHFUNCPROC glDepthFunc ;
        NATUS_OGL_API PFNGLPIXELSTOREFPROC glPixelStoref ;
        NATUS_OGL_API PFNGLPIXELSTOREIPROC glPixelStorei ;
        NATUS_OGL_API PFNGLREADBUFFERPROC glReadBuffer ;
        NATUS_OGL_API PFNGLREADPIXELSPROC glReadPixels ;
        NATUS_OGL_API PFNGLGETBOOLEANVPROC glGetBooleanv ;
        NATUS_OGL_API PFNGLGETDOUBLEVPROC glGetDoublev ;
        NATUS_OGL_API PFNGLGETERRORPROC glGetError ;
        NATUS_OGL_API PFNGLGETFLOATVPROC glGetFloatv ;
        NATUS_OGL_API PFNGLGETINTEGERVPROC glGetIntegerv ;
        NATUS_OGL_API PFNGLGETSTRINGPROC glGetString ;
        NATUS_OGL_API PFNGLGETTEXIMAGEPROC glGetTexImage ;
        NATUS_OGL_API PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv ;
        NATUS_OGL_API PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv ;
        NATUS_OGL_API PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv ;
        NATUS_OGL_API PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv ;
        NATUS_OGL_API PFNGLISENABLEDPROC glIsEnabled ;
        NATUS_OGL_API PFNGLDEPTHRANGEPROC glDepthRange ;
        NATUS_OGL_API PFNGLVIEWPORTPROC glViewport ;

    // gl version 1.1

        NATUS_OGL_API PFNGLDRAWARRAYSPROC glDrawArrays ;
        NATUS_OGL_API PFNGLDRAWELEMENTSPROC glDrawElements ;
        NATUS_OGL_API PFNGLGETPOINTERVPROC glGetPointerv ;
        NATUS_OGL_API PFNGLPOLYGONOFFSETPROC glPolygonOffset ;
        NATUS_OGL_API PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D ;
        NATUS_OGL_API PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D ;
        NATUS_OGL_API PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D ;
        NATUS_OGL_API PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D ;
        NATUS_OGL_API PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D ;
        NATUS_OGL_API PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D ;
        NATUS_OGL_API PFNGLBINDTEXTUREPROC glBindTexture ;
        NATUS_OGL_API PFNGLDELETETEXTURESPROC glDeleteTextures ;
        NATUS_OGL_API PFNGLGENTEXTURESPROC glGenTextures ;
        NATUS_OGL_API PFNGLISTEXTUREPROC glIsTexture ;

    // gl version 1.2

        NATUS_OGL_API PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements ;
        NATUS_OGL_API PFNGLTEXIMAGE3DPROC glTexImage3D ;
        NATUS_OGL_API PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D ;
        NATUS_OGL_API PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D ;

    // gl version 1.3

        NATUS_OGL_API PFNGLACTIVETEXTUREPROC glActiveTexture ;
        NATUS_OGL_API PFNGLSAMPLECOVERAGEPROC glSampleCoverage ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D ;
        NATUS_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D ;
        NATUS_OGL_API PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage ;

    // gl version 1.4

        NATUS_OGL_API PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate ;
        NATUS_OGL_API PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays ;
        NATUS_OGL_API PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements ;
        NATUS_OGL_API PFNGLPOINTPARAMETERFPROC glPointParameterf ;
        NATUS_OGL_API PFNGLPOINTPARAMETERFVPROC glPointParameterfv ;
        NATUS_OGL_API PFNGLPOINTPARAMETERIPROC glPointParameteri ;
        NATUS_OGL_API PFNGLPOINTPARAMETERIVPROC glPointParameteriv ;
        NATUS_OGL_API PFNGLBLENDCOLORPROC glBlendColor ;
        NATUS_OGL_API PFNGLBLENDEQUATIONPROC glBlendEquation ;

    // gl version 1.5

        NATUS_OGL_API PFNGLGENQUERIESPROC glGenQueries  ;
        NATUS_OGL_API PFNGLDELETEQUERIESPROC glDeleteQueries ;
        NATUS_OGL_API PFNGLISQUERYPROC glIsQuery ;
        NATUS_OGL_API PFNGLBEGINQUERYPROC glBeginQuery ;
        NATUS_OGL_API PFNGLENDQUERYPROC glEndQuery ;
        NATUS_OGL_API PFNGLGETQUERYIVPROC glGetQueryiv ;
        NATUS_OGL_API PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv ;
        NATUS_OGL_API PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv ;
        NATUS_OGL_API PFNGLBINDBUFFERPROC glBindBuffer ;
        NATUS_OGL_API PFNGLDELETEBUFFERSPROC glDeleteBuffers ;
        NATUS_OGL_API PFNGLGENBUFFERSPROC glGenBuffers ;
        NATUS_OGL_API PFNGLISBUFFERPROC glIsBuffer ;
        NATUS_OGL_API PFNGLBUFFERDATAPROC glBufferData ;
        NATUS_OGL_API PFNGLBUFFERSUBDATAPROC glBufferSubData ;
        NATUS_OGL_API PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData ;
        NATUS_OGL_API PFNGLMAPBUFFERPROC glMapBuffer ;
        NATUS_OGL_API PFNGLUNMAPBUFFERPROC glUnmapBuffer ;
        NATUS_OGL_API PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv ;
        NATUS_OGL_API PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv ;

    // gl version 2.0

        NATUS_OGL_API PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate  ;
        NATUS_OGL_API PFNGLDRAWBUFFERSPROC glDrawBuffers ;
        NATUS_OGL_API PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate ;
        NATUS_OGL_API PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate ;
        NATUS_OGL_API PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate ;
        NATUS_OGL_API PFNGLATTACHSHADERPROC glAttachShader ;
        NATUS_OGL_API PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation ;
        NATUS_OGL_API PFNGLCOMPILESHADERPROC glCompileShader ;
        NATUS_OGL_API PFNGLCREATEPROGRAMPROC glCreateProgram ;
        NATUS_OGL_API PFNGLCREATESHADERPROC glCreateShader ;
        NATUS_OGL_API PFNGLDELETEPROGRAMPROC glDeleteProgram ;
        NATUS_OGL_API PFNGLDELETESHADERPROC glDeleteShader ;
        NATUS_OGL_API PFNGLDETACHSHADERPROC glDetachShader ;
        NATUS_OGL_API PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray ;
        NATUS_OGL_API PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray ;
        NATUS_OGL_API PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib ;
        NATUS_OGL_API PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform ;
        NATUS_OGL_API PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders ;
        NATUS_OGL_API PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation ;
        NATUS_OGL_API PFNGLGETPROGRAMIVPROC glGetProgramiv ;
        NATUS_OGL_API PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog ;
        NATUS_OGL_API PFNGLGETSHADERIVPROC glGetShaderiv ;
        NATUS_OGL_API PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog ;
        NATUS_OGL_API PFNGLGETSHADERSOURCEPROC glGetShaderSource ;
        NATUS_OGL_API PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation ;
        NATUS_OGL_API PFNGLGETUNIFORMFVPROC glGetUniformfv ;
        NATUS_OGL_API PFNGLGETUNIFORMIVPROC glGetUniformiv ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv ;
        NATUS_OGL_API PFNGLISPROGRAMPROC glIsProgram ;
        NATUS_OGL_API PFNGLISSHADERPROC glIsShader ;
        NATUS_OGL_API PFNGLLINKPROGRAMPROC glLinkProgram ;
        NATUS_OGL_API PFNGLSHADERSOURCEPROC glShaderSource ;
        NATUS_OGL_API PFNGLUSEPROGRAMPROC glUseProgram ;
        NATUS_OGL_API PFNGLUNIFORM1FPROC glUniform1f ;
        NATUS_OGL_API PFNGLUNIFORM2FPROC glUniform2f ;
        NATUS_OGL_API PFNGLUNIFORM3FPROC glUniform3f ;
        NATUS_OGL_API PFNGLUNIFORM4FPROC glUniform4f ;
        NATUS_OGL_API PFNGLUNIFORM1IPROC glUniform1i ;
        NATUS_OGL_API PFNGLUNIFORM2IPROC glUniform2i ;
        NATUS_OGL_API PFNGLUNIFORM3IPROC glUniform3i ;
        NATUS_OGL_API PFNGLUNIFORM4IPROC glUniform4i ;
        NATUS_OGL_API PFNGLUNIFORM1FVPROC glUniform1fv ;
        NATUS_OGL_API PFNGLUNIFORM2FVPROC glUniform2fv ;
        NATUS_OGL_API PFNGLUNIFORM3FVPROC glUniform3fv ;
        NATUS_OGL_API PFNGLUNIFORM4FVPROC glUniform4fv ;
        NATUS_OGL_API PFNGLUNIFORM1IVPROC glUniform1iv ;
        NATUS_OGL_API PFNGLUNIFORM2IVPROC glUniform2iv ;
        NATUS_OGL_API PFNGLUNIFORM3IVPROC glUniform3iv ;
        NATUS_OGL_API PFNGLUNIFORM4IVPROC glUniform4iv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv ;
        NATUS_OGL_API PFNGLVALIDATEPROGRAMPROC glValidateProgram ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s ;
        NATUS_OGL_API PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s ;
        NATUS_OGL_API PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s ;
        NATUS_OGL_API PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer ;

    // gl version 2.1

        NATUS_OGL_API PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv ;

    // gl version 3.0

        NATUS_OGL_API PFNGLCOLORMASKIPROC glColorMaski ;
        NATUS_OGL_API PFNGLGETBOOLEANI_VPROC glGetBooleani_v ;
        NATUS_OGL_API PFNGLGETINTEGERI_VPROC glGetIntegeri_v ;
        NATUS_OGL_API PFNGLENABLEIPROC glEnablei ;
        NATUS_OGL_API PFNGLDISABLEIPROC glDisablei ;
        NATUS_OGL_API PFNGLISENABLEDIPROC glIsEnabledi ;
        NATUS_OGL_API PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback ;
        NATUS_OGL_API PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback ;
        NATUS_OGL_API PFNGLBINDBUFFERRANGEPROC glBindBufferRange ;
        NATUS_OGL_API PFNGLBINDBUFFERBASEPROC glBindBufferBase ;
        NATUS_OGL_API PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings ;
        NATUS_OGL_API PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying ;
        NATUS_OGL_API PFNGLCLAMPCOLORPROC glClampColor ;
        NATUS_OGL_API PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender ;
        NATUS_OGL_API PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender ;
        NATUS_OGL_API PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4SVPROC  glVertexAttribI4sv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv ;
        NATUS_OGL_API PFNGLGETUNIFORMUIVPROC glGetUniformuiv ;
        NATUS_OGL_API PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation ;
        NATUS_OGL_API PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation ;
        NATUS_OGL_API PFNGLUNIFORM1UIPROC glUniform1ui ;
        NATUS_OGL_API PFNGLUNIFORM2UIPROC glUniform2ui ;
        NATUS_OGL_API PFNGLUNIFORM3UIPROC glUniform3ui ;
        NATUS_OGL_API PFNGLUNIFORM4UIPROC glUniform4ui ;
        NATUS_OGL_API PFNGLUNIFORM1UIVPROC glUniform1uiv ;
        NATUS_OGL_API PFNGLUNIFORM2UIVPROC glUniform2uiv ;
        NATUS_OGL_API PFNGLUNIFORM3UIVPROC glUniform3uiv ;
        NATUS_OGL_API PFNGLUNIFORM4UIVPROC glUniform4uiv ;
        NATUS_OGL_API PFNGLTEXPARAMETERIIVPROC glTexParameterIiv ;
        NATUS_OGL_API PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv ;
        NATUS_OGL_API PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv ;
        NATUS_OGL_API PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv ;
        NATUS_OGL_API PFNGLCLEARBUFFERIVPROC glClearBufferiv ;
        NATUS_OGL_API PFNGLCLEARBUFFERUIVPROC glClearBufferuiv ;
        NATUS_OGL_API PFNGLCLEARBUFFERFVPROC glClearBufferfv ;
        NATUS_OGL_API PFNGLCLEARBUFFERFIPROC glClearBufferfi ;
        NATUS_OGL_API PFNGLGETSTRINGIPROC glGetStringi ;
        NATUS_OGL_API PFNGLISRENDERBUFFERPROC glIsRenderbuffer ;
        NATUS_OGL_API PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer ;
        NATUS_OGL_API PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers ;
        NATUS_OGL_API PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers ;
        NATUS_OGL_API PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage ;
        NATUS_OGL_API PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv ;
        NATUS_OGL_API PFNGLISFRAMEBUFFERPROC glIsFramebuffer ;
        NATUS_OGL_API PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer ;
        NATUS_OGL_API PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers ;
        NATUS_OGL_API PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers ;
        NATUS_OGL_API PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus ;
        NATUS_OGL_API PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D ;
        NATUS_OGL_API PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D ;
        NATUS_OGL_API PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D ;
        NATUS_OGL_API PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer ;
        NATUS_OGL_API PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv ;
        NATUS_OGL_API PFNGLGENERATEMIPMAPPROC glGenerateMipmap ;
        NATUS_OGL_API PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer ;
        NATUS_OGL_API PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample ;
        NATUS_OGL_API PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer ;
        NATUS_OGL_API PFNGLMAPBUFFERRANGEPROC glMapBufferRange ;
        NATUS_OGL_API PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange ;
        NATUS_OGL_API PFNGLBINDVERTEXARRAYPROC glBindVertexArray ;
        NATUS_OGL_API PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays ;
        NATUS_OGL_API PFNGLGENVERTEXARRAYSPROC glGenVertexArrays ;
        NATUS_OGL_API PFNGLISVERTEXARRAYPROC glIsVertexArray ;

    // gl version 3.1

        NATUS_OGL_API PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced ;
        NATUS_OGL_API PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced ;
        NATUS_OGL_API PFNGLTEXBUFFERPROC glTexBuffer ;
        NATUS_OGL_API PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex ;
        NATUS_OGL_API PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData ;
        NATUS_OGL_API PFNGLGETUNIFORMINDICESPROC glGetUniformIndices ;
        NATUS_OGL_API PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv ;
        NATUS_OGL_API PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName ;
        NATUS_OGL_API PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex ;
        NATUS_OGL_API PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv ;
        NATUS_OGL_API PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName ;
        NATUS_OGL_API PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding ;

    // gl version 3.2

        NATUS_OGL_API PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex ;
        NATUS_OGL_API PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex ;
        NATUS_OGL_API PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex ;
        NATUS_OGL_API PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex ;
        NATUS_OGL_API PFNGLPROVOKINGVERTEXPROC glProvokingVertex ;
        NATUS_OGL_API PFNGLFENCESYNCPROC glFenceSync ;
        NATUS_OGL_API PFNGLISSYNCPROC glIsSync ;
        NATUS_OGL_API PFNGLDELETESYNCPROC glDeleteSync ;
        NATUS_OGL_API PFNGLCLIENTWAITSYNCPROC glClientWaitSync ;
        NATUS_OGL_API PFNGLWAITSYNCPROC glWaitSync ;
        NATUS_OGL_API PFNGLGETINTEGER64VPROC glGetInteger64v ;
        NATUS_OGL_API PFNGLGETSYNCIVPROC glGetSynciv ;
        NATUS_OGL_API PFNGLGETINTEGER64I_VPROC glGetInteger64i_v ;
        NATUS_OGL_API PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v ;
        NATUS_OGL_API PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture ;
        NATUS_OGL_API PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample ;
        NATUS_OGL_API PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample ;
        NATUS_OGL_API PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv ;
        NATUS_OGL_API PFNGLSAMPLEMASKIPROC glSampleMaski ;

    // gl version 3.3

        NATUS_OGL_API PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed ;
        NATUS_OGL_API PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex ;
        NATUS_OGL_API PFNGLGENSAMPLERSPROC glGenSamplers ;
        NATUS_OGL_API PFNGLDELETESAMPLERSPROC glDeleteSamplers ;
        NATUS_OGL_API PFNGLISSAMPLERPROC glIsSampler ;
        NATUS_OGL_API PFNGLBINDSAMPLERPROC glBindSampler ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv ;
        NATUS_OGL_API PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv ;
        NATUS_OGL_API PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv ;
        NATUS_OGL_API PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv ;
        NATUS_OGL_API PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv ;
        NATUS_OGL_API PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv ;
        NATUS_OGL_API PFNGLQUERYCOUNTERPROC glQueryCounter ;
        NATUS_OGL_API PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v ;
        NATUS_OGL_API PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v ;
        NATUS_OGL_API PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui ;
        NATUS_OGL_API PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv ;

    // gl version 4.0

        NATUS_OGL_API PFNGLMINSAMPLESHADINGPROC glMinSampleShading ;
        NATUS_OGL_API PFNGLBLENDEQUATIONIPROC glBlendEquationi ;
        NATUS_OGL_API PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei ;
        NATUS_OGL_API PFNGLBLENDFUNCIPROC glBlendFunci ;
        NATUS_OGL_API PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei ;
        NATUS_OGL_API PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect ;
        NATUS_OGL_API PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect ;
        NATUS_OGL_API PFNGLUNIFORM1DPROC glUniform1d ;
        NATUS_OGL_API PFNGLUNIFORM2DPROC glUniform2d ;
        NATUS_OGL_API PFNGLUNIFORM3DPROC glUniform3d ;
        NATUS_OGL_API PFNGLUNIFORM4DPROC glUniform4d ;
        NATUS_OGL_API PFNGLUNIFORM1DVPROC glUniform1dv ;
        NATUS_OGL_API PFNGLUNIFORM2DVPROC glUniform2dv ;
        NATUS_OGL_API PFNGLUNIFORM3DVPROC glUniform3dv ;
        NATUS_OGL_API PFNGLUNIFORM4DVPROC glUniform4dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv ;
        NATUS_OGL_API PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv ;
        NATUS_OGL_API PFNGLGETUNIFORMDVPROC glGetUniformdv ;
        NATUS_OGL_API PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation ;
        NATUS_OGL_API PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex ;
        NATUS_OGL_API PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv ;
        NATUS_OGL_API PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName ;
        NATUS_OGL_API PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName ;
        NATUS_OGL_API PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv ;
        NATUS_OGL_API PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv ;
        NATUS_OGL_API PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv ;
        NATUS_OGL_API PFNGLPATCHPARAMETERIPROC glPatchParameteri ;
        NATUS_OGL_API PFNGLPATCHPARAMETERFVPROC glPatchParameterfv ;
        NATUS_OGL_API PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback ;
        NATUS_OGL_API PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks ;
        NATUS_OGL_API PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks ;
        NATUS_OGL_API PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback ;
        NATUS_OGL_API PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback ;
        NATUS_OGL_API PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback ;
        NATUS_OGL_API PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback ;
        NATUS_OGL_API PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream ;
        NATUS_OGL_API PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed ;
        NATUS_OGL_API PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed ;
        NATUS_OGL_API PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv ;

    // gl version 4.1

        NATUS_OGL_API PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler ;
        NATUS_OGL_API PFNGLSHADERBINARYPROC glShaderBinary ;
        NATUS_OGL_API PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat ;
        NATUS_OGL_API PFNGLDEPTHRANGEFPROC glDepthRangef ;
        NATUS_OGL_API PFNGLCLEARDEPTHFPROC glClearDepthf ;
        NATUS_OGL_API PFNGLGETPROGRAMBINARYPROC glGetProgramBinary ;
        NATUS_OGL_API PFNGLPROGRAMBINARYPROC glProgramBinary ;
        NATUS_OGL_API PFNGLPROGRAMPARAMETERIPROC glProgramParameteri ;
        NATUS_OGL_API PFNGLUSEPROGRAMSTAGESPROC  glUseProgramStages ;
        NATUS_OGL_API PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram ;
        NATUS_OGL_API PFNGLCREATESHADERPROGRAMVPROC  glCreateShaderProgramv ;
        NATUS_OGL_API PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline ;
        NATUS_OGL_API PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines ;
        NATUS_OGL_API PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines ;
        NATUS_OGL_API PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline ;
        NATUS_OGL_API PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1IPROC  glProgramUniform1i ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1IVPROC  glProgramUniform1iv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv ;
        NATUS_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv ;
        NATUS_OGL_API PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline ;
        NATUS_OGL_API PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d  ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv ;
        NATUS_OGL_API PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer ;
        NATUS_OGL_API PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv ;
        NATUS_OGL_API PFNGLVIEWPORTARRAYVPROC glViewportArrayv ;
        NATUS_OGL_API PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf ;
        NATUS_OGL_API PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv ;
        NATUS_OGL_API PFNGLSCISSORARRAYVPROC glScissorArrayv ;
        NATUS_OGL_API PFNGLSCISSORINDEXEDPROC glScissorIndexed ;
        NATUS_OGL_API PFNGLSCISSORINDEXEDVPROC glScissorIndexedv ;
        NATUS_OGL_API PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv ;
        NATUS_OGL_API PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed ;
        NATUS_OGL_API PFNGLGETFLOATI_VPROC glGetFloati_v ;
        NATUS_OGL_API PFNGLGETDOUBLEI_VPROC glGetDoublei_v ;
    }
}
