
os: Visual Studio 2019

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 ..
  - cmake --build . --config Release
  
