
image: 
  - Ubuntu
  - Visual Studio 2019  

install:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - sh: cd $APPVEYOR_BUILD_FOLDER
  - git submodule update --init --recursive

build_script:
  - cmd: md build
  - sh: mkdir build
  - cd build
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 ..
  - sh: cmake -G "Unix Makefiles" -A x64 -DNATUS_TARGET_GRAPHICS_API=null ..
  - cmake --build . --config Release
  
