

#
#
#

set( NATUS_BUILD_ENV_CONFIGURED FALSE )

set( NATUS_BUILD_ENV_MSVS OFF )
set( NATUS_BUILD_ENV_MINGW OFF )
set( NATUS_BUILD_ENV_CYGWIN OFF )
set( NATUS_BUILD_ENV_MAKE OFF )

set( NATUS_BUILD_ENV_CONFIGURED TRUE )

if( MSVC_IDE  )
    set( NATUS_BUILD_ENV_MSVS ON )
endif()

